[package]
name = "tetris"
version = "0.1.0"
edition = "2021"
authors = ["Ziloka <50429450+ziloka@users.noreply.github.com>"]

[dependencies]
macroquad = "0.3.25"
# quad-storage = "0.1.3"
# quad-net = "0.1.1"
# cold-clear-2 = { git = "https://github.com/MinusKelvin/cold-clear-2" }
# https://github.com/thesilican/tetris-ai

[profile.release]
strip = true 
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
