[package]
name = "tetris"
version = "0.1.0"
edition = "2021"
authors = ["Ziloka <50429450+ziloka@users.noreply.github.com>"]

[dependencies]
macroquad = "0.3.25"
# cold-clear-2 = { git = "https://github.com/MinusKelvin/cold-clear-2" }

[profile.release]
strip = true 
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
