[package]
name = "tetris"
version = "0.1.0"
edition = "2021"
authors = ["Ziloka <50429450+ziloka@users.noreply.github.com>"]

[dependencies]
macroquad = "0.3.25"
# egui = "0.20.1"
# egui-macroquad = { version = "0.12.0", git = "https://github.com/ziloka/egui-macroquad", rev = "069cbffb86c88b8bcf886fbf8eedbb4198a9fdc8"}
# egui-bind = "0.5.2"
# cold-clear-2 = { git = "https://github.com/MinusKelvin/cold-clear-2" }
# https://docs.rs/getrandom/latest/getrandom/#webassembly-support
# getrandom = { version = "*", features = ["js"] }