[package]
name = "tetris"
version = "0.1.0"
edition = "2021"
authors = ["Ziloka <50429450+ziloka@users.noreply.github.com>"]

[dependencies]
macroquad = "0.3"
# cold-clear-2 = { git = "https://github.com/MinusKelvin/cold-clear-2" }
# https://docs.rs/getrandom/latest/getrandom/#webassembly-support
# getrandom = { version = "*", features = ["js"] }