[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"

[profile.release]
strip = true 
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
